// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKFj6XOed1JiRGC6Z_C9LW9U-eayKGrk',
    appId: '1:428329879965:web:d32f5c9b3568372a3d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    authDomain: 'fir-4dbab.firebaseapp.com',
    storageBucket: 'fir-4dbab.appspot.com',
    measurementId: 'G-581MD3W3C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRnRSBaxEGqFBfBu2Gmuu7Q6EgMomdq8',
    appId: '1:428329879965:android:3f057ff8cbae083d3d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    storageBucket: 'fir-4dbab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPGopYFOu-sk1NXE0WnkiqdkbFl_1UCE',
    appId: '1:428329879965:ios:77a13c54d1fb08e73d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    storageBucket: 'fir-4dbab.appspot.com',
    iosBundleId: 'com.abrehotsolutions.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvPGopYFOu-sk1NXE0WnkiqdkbFl_1UCE',
    appId: '1:428329879965:ios:77a13c54d1fb08e73d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    storageBucket: 'fir-4dbab.appspot.com',
    iosBundleId: 'com.abrehotsolutions.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsKFj6XOed1JiRGC6Z_C9LW9U-eayKGrk',
    appId: '1:428329879965:web:0ce2594f747f64b43d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    authDomain: 'fir-4dbab.firebaseapp.com',
    storageBucket: 'fir-4dbab.appspot.com',
    measurementId: 'G-4WNPC0EVEZ',
  );
}
